# -*- coding: utf-8 -*-

"""
/***************************************************************************
 DeepForestPlugin
                                 A QGIS plugin
 Plugin using DeepForest to detect trees
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-21
        copyright            : (C) 2023 by PXL Smart ICT
        email                : servaas.tilkin@pxl.be
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'PXL Smart ICT'
__date__ = '2023-02-21'
__copyright__ = '(C) 2023 by PXL Smart ICT'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from osgeo import gdal
import numpy as np
from PIL import Image
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsVectorLayer,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterNumber,
                       QgsPointXY)


# https://www.qgistutorials.com/en/docs/3/processing_python_plugin.html
# https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/cheat_sheet.html#layers
class DeepForestPluginAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    INPUT_LIMIT = 'INPUT_LIMIT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        print('initAlgorithm')

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr('Input layer'),
                None,
                False
            )
        )

        # Add window parameter for algorithm
        self.addParameter(
            QgsProcessingParameterNumber(
                self.INPUT_LIMIT,
                self.tr('Window size in pixels (should be about 40m)'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=600,
                optional=False,
                minValue=0,
                maxValue=10000,
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                self.tr('Output file'),
                optional=False,
                fileFilter='Image files (*.png)'
                # fileFilter='GeoJSON files (*.json)'
            )
        )

    # https://github.com/geoscan/geoscan_forest
    # https://bitbucket.org/kul-reseco/localmaxfilter/src/master/localmaxfilter/interfaces/localmaxfilter_processing.py
    # https://gis.stackexchange.com/questions/282773/writing-a-python-processing-script-with-qgis-3-0
    # https://gis.stackexchange.com/questions/358230/programmatically-enable-disable-input-parameters-in-a-qgis-processing-plugin
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        print('processAlgorithm')

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.

        source_layer = self.parameterAsRasterLayer(parameters, self.INPUT, context)
        window_size = self.parameterAsInt(parameters, self.INPUT_LIMIT, context)
        dest_file = self.parameterAsFileOutput(parameters, self.OUTPUT, context)

        source_provider = source_layer.dataProvider()
        ds_uri = str(source_provider.dataSourceUri())
        gdal_dsm = gdal.Open(ds_uri)

        print(str(source_layer))
        print(source_layer.width(), source_layer.height())
        rect = source_layer.extent()
        print(rect)
        print(rect.width())
        print(rect.height())

        ds = gdal.Open(source_layer.dataProvider().dataSourceUri())
        print('RasterCount  ' + str(ds.RasterCount))
        arr_1 = ds.GetRasterBand(1).ReadAsArray()
        arr_2 = ds.GetRasterBand(2).ReadAsArray()
        arr_3 = ds.GetRasterBand(3).ReadAsArray()
        three_band = np.array([arr_1, arr_2, arr_3])
        print(three_band.shape)
        # three_band = np.swapaxes(three_band, 0, 2)
        # three_band = np.swapaxes(three_band, 0, 1)
        three_band = np.transpose(three_band, (1, 2, 0))
        print(three_band.shape)

        # val, res = source_layer.dataProvider().sample(QgsPointXY(679623, 5641193), 1)

        print(str(window_size))
        print(str(dest_file))

        img = Image.fromarray(three_band, 'RGB')
        img.save(dest_file)

        # (sink, dest_id) = self.parameterAsRasterLayer(parameters, self.OUTPUT, context, None, None, None)
        #
        # # Compute the number of steps to display within the progress bar and
        # # get features from source
        # total = 100.0 / source.featureCount() if source.featureCount() else 0
        # features = source.getFeatures()
        #
        # for current, feature in enumerate(features):
        #     # Stop the algorithm if cancel button has been clicked
        #     if feedback.isCanceled():
        #         break
        #
        #     # Add a feature in the sink
        #     sink.addFeature(feature, QgsFeatureSink.FastInsert)
        #
        #     # Update the progress bar
        #     feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.

        # TODO: write JSON file
        # TODO: return as output

        return {self.OUTPUT: None}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Detect Trees'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return DeepForestPluginAlgorithm()
